name: 'Spin - Google Cloud GKE cluster.'
description: 'GitHub Action to create GKE cluster'
branding:
  icon: 'cloud-lightning'
  color: 'blue'
inputs:
  APPLICATION_CREDENTIALS:
    description: 'GCP authorization credentials'
    required: true
  PROJECT_ID:
    description: 'Project id'
    required: true
  CLUSTER_NAME:
    description: 'GKE Cluser Name'
    required: true
  ZONE_NAME:
    description: 'Zone Name'
    required: true
  GITHUB_WORKSPACE:
    description: 'Export credentials if requested - these credentials must be exported in the shared workspace directory, since the filesystem must be shared among all steps.'
    required: false
    default: env.GITHUB_WORKSPACE
runs:
  using: 'docker'
  image: 'Dockerfile'
