name: 'Spin - Google Cloud GKE cluster.'
description: 'GitHub Action to create GKE cluster'
branding:
  icon: 'cloud-lightning'
  color: 'blue'
inputs:
  APPLICATION_CREDENTIALS:
    description: 'GCP authorization credentials'
    required: true
  PROJECT_ID:
    description: 'Project id'
    required: true
  CLUSTER_NAME:
    description: 'GKE Cluser Name'
    required: true
  ZONE_NAME:
    description: 'Zone Name'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
